Algoritmo "contar"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/12/2019
Var
// Seção de Declarações das variáveis 
   contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   contador <- 0
   Enquanto (contador<=10) faca
            EscrevAL (contador)
            contador <- contador + 1
   FimEnquanto


Fimalgoritmo