Algoritmo "conversao_graus"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/11/2019
Var
// Seção de Declarações das variáveis 
   C,F,R: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva ("Qual a temperatura de onde você está? ")
   Leia (F)
   C<- (F-32)/1.8
   EscREva ("A temperatura em graus celsios é ", C)
   
   

Fimalgoritmo