Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/11/2019
Var
// Seção de Declarações das variáveis 
   valor, imposto : Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva ("Qual o valor do produto? US$")
   Leia (valor)
   imposto <- (valor*60)/100
   Escreva ("O imposto será de ", imposto, "U$")
   
   

Fimalgoritmo